# .cnb.yml
$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - docker:
        # 自定义开发环境
        build:
          # 指定构建镜像的 Dockerfile 文件
          dockerfile: .ide/Dockerfile
          # 用来声明缓存构建过程中依赖的文件列表。
        volumes:
          # 缓存文件
          - node_modules:copy-on-write
      services:
        # 声明使用 vscode 服务
        - vscode
        # 声明在容器中支持 docker 命令
        - docker
      stages:
        # 环境启动后需要执行的命令
        - name: 安装依赖
          script: yarn
# WebIDE 修改不触发发流水线
.skip_project: &skip_project
  ifModify:
    - "**"
    - "!(.ide/**)"
main:
  push:
    - name: "向量化数据"
      stages:
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            include: "**/**.md"
    - name: "推送镜像"
      imports:
        - https://cnb.cool/Mintimate/secret/-/blob/main/SyncToGitHub.yml
      stages:
        - name: 自动同步代码
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Mintimate/DocVitePressOMR.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            force: true
    - name: "构建产物"
      docker:        
        image: node:22
        volumes:
          - /root/.npm:copy-on-write
          - node_modules:copy-on-write
      stages:
        - name: 安装依赖
          script: yarn
        - name: 构建产物
          script: yarn build
        - name: "部署流程"
          imports:
            - https://cnb.cool/Mintimate/secret/-/blob/main/DocVitePressOMR.yaml
          image: tencentcom/deploy-eopages:latest
          script: 
            - cd .vitepress
            - edgeone pages deploy ./dist -n oh-my-rime -t $EO_SECRET