# .cnb.yml
$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - docker:
        # 自定义开发环境
        build:
          # 指定构建镜像的 Dockerfile 文件
          dockerfile: .ide/Dockerfile
          # 用来声明缓存构建过程中依赖的文件列表。
        volumes:
          # 缓存文件
          - node_modules:copy-on-write
      services:
        # 声明使用 vscode 服务
        - vscode
        # 声明在容器中支持 docker 命令
        - docker
      stages:
        # 环境启动后需要执行的命令
        - name: 安装依赖
          script: yarn
  # 标签事件
  tag_push:
    # 上传二进制包到 release 附件
    - docker:
        build: .ide/Dockerfile
      imports:
        - https://cnb.cool/Mintimate/secret/-/blob/main/SyncToGitHub.yml
      stages:
        - name: 创建日期
          script: 
            - DATETIME_TAG=$(date +%Y-%m-%d)
            - echo "##[set-output DATETIME_TAG=$(echo "$DATETIME_TAG")]"
          exports:
            DATETIME_TAG: DATETIME_TAG
        - name: 创建发布标签
          type: git:release
          options:
            title: ${DATETIME_TAG}
            description: Auto Sync at ${DATETIME_TAG}
            latest: true
        - name: 下载上游客户端
          script: 
            # 下载 weasel .exe 文件并设置输出变量
            - weasel_url=$(curl -sL -H "Authorization:\ Bearer ${GIT_PUBLIC_ACCESS_TOKEN}" https://api.github.com/repos/rime/weasel/releases/latest | grep -Eo 'https://[^"]+\.exe' | head -1)
            - weasel_file=$(basename "$weasel_url")
            - curl -LO "$weasel_url"
            - mv "$weasel_file" weasel-installer-latest.exe
            - echo "##[set-output weasel_file=$(echo "$weasel_file")]"
            # 下载 squirrel .pkg 文件并设置输出变量
            - squirrel_url=$(curl -sL -H "Authorization:\ Bearer ${GIT_PUBLIC_ACCESS_TOKEN}" https://api.github.com/repos/rime/squirrel/releases/latest | grep -Eo 'https://[^"]+\.pkg' | head -1)
            - squirrel_file=$(basename "$squirrel_url")
            - curl -LO "$squirrel_url"
            - mv "$squirrel_file" Squirrel-latest.pkg
            - echo "##[set-output squirrel_file=$(echo "$squirrel_file")]"
            # 下载 Fctix5-macOS installer 文件并设置输出变量
            - fctix5_macOS_url=$(curl -sL -H "Authorization:\ Bearer ${GIT_PUBLIC_ACCESS_TOKEN}" https://api.github.com/repos/fcitx-contrib/fcitx5-macos-installer/releases/latest | grep -Eo 'https://[^"]+Rime.zip' | head -1)
            - fctix5_macOS_file=$(basename "$fctix5_macOS_url")
            - curl -LO "$fctix5_macOS_url" -o "$(basename "$fctix5_macOS_url")"
            - echo "##[set-output fctix5_macOS_file=$(echo "$fctix5_macOS_file")]"
            # 下载 万象语言模型 文件并设置输出变量
            - wanxiang_url=$(curl -sL -H "Authorization:\ Bearer ${GIT_PUBLIC_ACCESS_TOKEN}" https://api.github.com/repos/amzxyz/RIME-LMDG/releases/tags/LTS | grep -Eo 'https://[^"]+\.gram' | head -1)
            - wanxiang_file=$(basename "$wanxiang_url")
            - curl -LO "$wanxiang_url" -o “$wanxiang_file”
            - echo "##[set-output wanxiang_file=$(echo "$wanxiang_file")]"
          exports:
            weasel_file: weasel_file
            squirrel_file: squirrel_file
            fctix5_macOS_file: fctix5_macOS_file
            wanxiang_file: wanxiang_file
        - name: 自动打包薄荷在线方案包
          image: docker.cnb.cool/mintimate/rime/deploy-schema
          settings:
            user_recipe_list: 'Mintimate/oh-my-rime:plum/full'
            package_items: 'build opencc lua'
            zip_file: oh-my-rime-online.zip
        - name: 自动打包雾凇在线方案包
          image: docker.cnb.cool/mintimate/rime/deploy-schema
          settings:
            user_recipe_list: 'iDvel/rime-ice:others/recipes/full'
            package_items: 'build opencc lua'
            zip_file: rime-ice-online.zip
        - name: release 上传附件
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - $weasel_file
              - $squirrel_file
              - $fctix5_macOS_file
              - $wanxiang_file
              - oh-my-rime-online.zip
              - rime-ice-online.zip
# WebIDE 修改不触发发流水线
.skip_project: &skip_project
  ifModify:
    - "**"
    - "!(.ide/**)"
main:
  push:
    - name: "向量化数据"
      stages:
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            include: "**/**.md"
    - name: "推送镜像"
      imports:
        - https://cnb.cool/Mintimate/secret/-/blob/main/SyncToGitHub.yml
      stages:
        - name: 自动同步代码
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Mintimate/DocVitePressOMR.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            force: true
    - name: "构建产物"
      imports:
        - https://cnb.cool/Mintimate/secret/-/blob/main/DocVitePressOMR.yaml
      docker:        
        image: node:22
        volumes:
          - /root/.npm:copy-on-write
          - node_modules:copy-on-write
      stages:
        - name: 安装依赖
          script: yarn
        - name: 构建产物
          script: yarn build
        - name: "部署流程"
          image: tencentcom/deploy-eopages:latest
          script: 
            - cd .vitepress
            - edgeone pages deploy ./dist -n oh-my-rime -t $EO_SECRET
  "crontab: 0 0 */7 * *":
    - stages:
      - name: release clean
        image: docker.cnb.cool/cnb/plugins/cnbcool/release-clean:latest
        settings:
          filter: "RECENT_N=2"
          debug: false
      - name: 制作标签
        script: 
          - DATETIME_TAG=$(date +%Y-%m-%d)
          - git tag -a "$DATETIME_TAG" -m "Auto Sync at $DATETIME_TAG"
          - git push origin "$DATETIME_TAG" -f