# .cnb.yml
$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - docker:
        image: docker.cnb.cool/flyinbug/dev-ops/nodejs:latest
        volumes:
          - node_modules:copy-on-write
      services:
        - vscode
        - docker
      stages:
        - name: 安装依赖
          script: yarn

  # 标签事件
  tag_push:
    - imports:
        - .cnb/pipeline/release.yml

# WebIDE 修改不触发发流水线
.skip_project: &skip_project
  ifModify:
    - "**"
    - "!(.ide/**)"

main:
  push:
    - name: "向量化数据"
      stages:
        - name: build knowledge base
          type: knowledge:update
          options:
            include: "**/*.md"
    - imports:
        - .cnb/pipeline/push.yml
        - .cnb/pipeline/build.yml
    - imports:
        - .cnb/pipeline/clean.yml
