# .cnb.yml - 仅包含 include 列表
include:
  - .cnb/pipeline/tag-push.yml
  - .cnb/pipeline/main-push.yml

# WebIDE 修改不触发流水线
.skip_project: &skip_project
  ifModify:
    - "**"
    - "!(.ide/**)"

# vscode 开发环境
$:
  vscode:
    - docker:
        image: docker.cnb.cool/flyinbug/dev-ops/nodejs:latest
        volumes:
          - node_modules:copy-on-write
      services:
        - vscode
        - docker
      stages:
        - name: 安装依赖
          script: yarn
