name: Auto Deploy
# 触发workflow的条件
on:
  push:
    # 只有main提交才会触发workflow
    branches: main

env:
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  USER_NAME: ${{ secrets.SERVER_USER }} # 服务器用户名
  TARGET_PATH: ${{ secrets.SERVER_TARGET }} # 服务器的部署地址
  cache-name: note

# jobs表示执行的一项或多项任务
jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    if: github.repository_owner == 'Mintimate'
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v1
        with:
          node-version: v18.17.0

      #缓存依赖
      - name: Cache node module
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # 需要缓存的文件的路径
          path: ./node_modules
          # 对缓存的文件指定的唯一标识
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
          # 用于没有再找目标key的缓存的backup选项
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 装依赖
      - name: Install Module
        run: yarn

      # 打包
      - name: Build Project
        run: yarn build

      # 上传打包资源
      - name: Deploy To Host
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ env.SERVER_PRIVATE_KEY }}
          ARGS: '-avz --delete'
          SOURCE: '.vitepress/dist/'
          REMOTE_HOST: ${{ env.SERVER_HOST }}
          REMOTE_USER: ${{ env.USER_NAME }}
          TARGET: ${{ env.TARGET_PATH}}  # 服务器目标路径
          SCRIPT_BEFORE: |
            whoami
          SCRIPT_AFTER: |
            whoami
            echo $RSYNC_STDOUT

